productapp/urls.py
from django.conf.urls import url
from .import views
from django.views.generic import RedirectView

app_name='productapp'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^productapp/',RedirectView.as_view(pattern_name='productapp:index',permanent=True)),
    url(r'^product/list/',views.product_list,name='prolist'),
    url(r'^prolist/$',views.pro_list,name='mylist'),
    url(r'^mycarts/$',views.mycart, name='mycart-selection'),
    url(r'^cart/add/(?P<pk>\d+)/', views.cart_add, name='cart_add'),
    url(r'^cart/cart_clear/', views.cart_clear, name='cart_clear'),
    
]

productapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


"""
model for product category
"""
class Category(models.Model):
	CAT_MALE = 'male'
	CAT_FEMALE = 'female'
	CAT_CHILD = 'children'

	CATEGORY_CHOICES =(
		(CAT_MALE,'Male'),
		(CAT_FEMALE,'Female'),
		(CAT_CHILD,'Children'),
		)
	cat_name = models.CharField(max_length=100,choices=CATEGORY_CHOICES, null=True, blank=True)
	
	def __str__(self):		
		return self.cat_name

"""
model for the product size
"""
class Size(models.Model):
	LONG = 'long'
	MEDIUM = 'medium'
	SHORT = 'short'
	XL='xl'
	XXL='xxl'

	SIZE_CHOICES =(
		(LONG,'Long'),
		(MEDIUM,'Medium'),
		(SHORT,'Short'),
		(XL,'xl'),
		(XXL,'xxl')
		)
	size = models.CharField(max_length=50,choices=SIZE_CHOICES, null=True, blank=True)
	
	def __str__(self):		
		return self.size


"""
model for the product size
"""
class ProType(models.Model):
	SUMMER = 'summer'
	WINTER = 'winter'

	TYPE_CHOICES =(
		(SUMMER,'Summer'),
		(WINTER,'Winter'),
		)
	protype = models.CharField(max_length=50,choices=TYPE_CHOICES, null=True, blank=True)
	
	def __str__(self):		
		return self.protype


"""
product 
"""
class Product(models.Model):
	name = models.CharField(max_length=100)
	category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
	size = models.ManyToManyField(Size, help_text="select size of the product")
	product_type = models.ManyToManyField(ProType, help_text="select a product type")
	price = models.CharField(max_length=100, help_text="entet price of product")
	image = models.ImageField(upload_to='uploads/', null=True)
	
	def __str__(self):
		return self.product_title

	def get_absolute_url(self):
		return reverse('trooproduct:pro-detail', args=[str(self.id)])


"""
Mycart
"""
class mycart(models.Model):
	class Meta:
		ordering = ['item']		
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	item = models.CharField(max_length=200)
	
	def __str__():
		return '{} {}'.format(self.user, self.item)

productapp/views.py
import json
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, JsonResponse
from productapp.models import Product
from django.core import serializers
from cart.cart import Cart
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
	return render(request,'productapp/product_index.html')


"""
function for json response for list
"""
def pro_list(request):
	if request.method =='GET':		
		data = serializers.serialize("json", Product.objects.all())
		# data = 	Product.objects.values()
		# print(data)
		# stud_data = list(data)
		
		data = {
		'pro': data,
		}		
		return JsonResponse({'satus':'ok','stud_data':data} )
	else:
		return JsonResponse({'status':0})

@login_required
def product_list(request):
	pro = Product.objects.all()[:20]
	# import pdb;pdb.set_trace()
	# context = {
	# 	'prosss':pro
	# }
	# test = 'test'
	return render(request,'productapp/home.html',{'pro':pro})



def mycart(request):
	if request.method=='GET':
		mylist = []
		cartid = request.GET.get('id')
		mylist.append(cartid)
		data = {
		'res':mylist
		}
		# import pdb;pdb.set_trace()
		return JsonResponse(data)


def cart_add(request, pk):
    cart = Cart(request)
    product = Product.objects.get(id=pk)
    cart.add(product=product)
    return redirect(reverse("productapp/index"))


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect(reverse("productapp:cart_detail"))

productapp/templates/productapp/cart_detail.html
{% load cart_tag %}

Total Length :: {{request.session.cart|length}}

<h2>Cart Detail:</h2>

{% for key,value in request.session.cart.items %}

{{value.name}} {{value.price}} {{value.quantity}} {{value.image}} Total {{ value.price|multiply:value.quantity }}

{% endfor %}

productapp/templates/productapp/home.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Online Shoping page</title>
<link rel="stylesheet" type="text/css" href="{% static "css/usercrud-style.css" %}">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static "js/usercrud-js.js" %}"></script>
</head>

<script type="text/javascript">
	$.ajax({
		type:'GET',
		url: '{% url "productapp:mylist" %}',
		contentType: "application/json; charset=utf-8",
		data: {
			'id':'testid',
		},
		dataType: 'json',
		success: function(data){
			x = data.stud_data
			if(data){
				for(i=0;i<x.length;i++){
					output +="<tr><td>" + x[i].id + "</td><td>" + x[i].name + "</td><td>" + x[i].category + "</td><td>" + x[i].size + "</td><td>" + x[i].product_type + "</td><td>" + x[i].price +"</td><td><input type='button' class='btn btn-warning btn-sm' value='Edit' data-sid=" + x[i].id + " /> ";
				}
				$("#tbody").html(output)					
			}
		},
		error:function(e){
			console.log(e);
		},
	}); 	
</script>


<body>
    <div class="container">
		<div class="table-responsive">
			<div class="table-wrapper">
				<a href="{% url 'productapp:index' %}"><button type="button" class="btn btn-warning">Home</button></a>
				<div class="table-title">

					<div class="row">
						<div class="col-xs-6">
							<h2>choose <b>Products</b></h2>
						</div>
						<div class="col-xs-6">
							<a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Go to Cart</span></a>
												
						</div>
					</div>
				</div>
				<table class="table table-striped table-hover" >
					<thead>
						<tr>
							<th>SN</th>
							<th>Product</th>
							<th>Category</th>
							<th>Size</th>
							<th>Type</th>
							<th>Price</th>
							<th>Select</th>
						</tr>
					</thead>
					<tbody id="tbody"> 
						{% if pro %}						
												
						{% for pr in pro %}
						<tr>
							<td>{{ pr.id }}</td>
							
							<td>{{pr.name}}</td>
							<td>{{ pr.category}}</td>
							
							{% for sz in pr.size.all %}
							<td>{{ sz}}</td>
							{% endfor %}

							{% for typ in pr.product_type.all  %}
							<td>{{typ}}</td>
							{% endfor %}
							
							<td>{{ pr.price }}</td>
							<td>
								<span class="custom-checkbox">
									<input type="checkbox" id="checkbox1" name="options[]" value="{{ pr.id }}">
									<label for="checkbox1"></label>
									<!-- <a href="{% url 'productapp:cart_add' pr.pk %}">Add To Cart</a> -->
								</span>
							</td>
							
						</tr>
						{% endfor %}
						{% endif %}
						
						
						
					</tbody>
				</table>
				<div class="clearfix">
					<div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
					<ul class="pagination">
						<li class="page-item disabled"><a href="#">Previous</a></li>
						<li class="page-item"><a href="#" class="page-link">1</a></li>
						<li class="page-item"><a href="#" class="page-link">2</a></li>
						<li class="page-item active"><a href="#" class="page-link">3</a></li>
						<li class="page-item"><a href="#" class="page-link">4</a></li>
						<li class="page-item"><a href="#" class="page-link">5</a></li>
						<li class="page-item"><a href="#" class="page-link">Next</a></li>
					</ul>
				</div>
			</div>
		</div>        
    </div>
	<!-- Edit Modal HTML -->
	<div id="addEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>
					<div class="modal-header">						
						<h4 class="modal-title">My Cart Items</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<div class="form-group">
							<label>Item 1</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Item 2</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Item 3</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Item 4</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Item 5</label>
							<input type="text" class="form-control" required>
						</div>	
						<div class="form-group">
							<label>Item 6</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Item 7</label>
							<input type="text" class="form-control" required>
						</div>							
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Clear Cart">
						<input type="submit" class="btn btn-success" value="Go for payment">
					</div>
				</form>
			</div>
		</div>
	</div>
	
</body>
</html>

productapp/templates/productapp/home3.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Online Shoping page</title>
<link rel="stylesheet" type="text/css" href="{% static "css/usercrud-style.css" %}">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static "js/usercrud-js.js" %}"></script>

</head>


<script type="text/javascript">


	$.ajax({
		type:'GET',
		url: '{% url "productapp:mylist" %}',
		contentType: "application/json; charset=utf-8",
		data: {
			'id':123,
		},
		dataType: 'json',
		success: function(data){
			if(data){
				alert('success');	
			}

		},
		error:function(e){
			console.log(e);
		},

	}); 	


function reply_click(clicked_id){
		var selected_id = clicked_id;
		alert (selected_id);
	
	  	}

	  	function reply_click(clicked_id){
		var selected_id = clicked_id;
		// alert (selected_id);
	  	// alert(clicked_id);
		$.ajax({
			type:'GET',
			url: '{% url "productapp:mycart-selection" %}',
			contentType: "application/json; charset=utf-8", 
			data: {
				'id':selected_id,
			},
			dataType : 'json',
			success: function(data){
				
				if(data){
					debugger;
					alert('ok');		
									
				}					
				
			},
			error:function(e){
				
				console.log(e);
			},
		});
	  	}	

</script>


<body>
    <div class="container">
    	Test
    
		<div class="table-responsive">
			<div class="table-wrapper">
				<div class="table-title">
					<div class="row">
						<div class="col-xs-6">
							<h2>choose <b>Products</b></h2>
						</div>
						<div class="col-xs-6">
							<a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Go to Cart</span></a>
												
						</div>
					</div>
				</div>
				<table class="table table-striped table-hover" >
					<thead>
						<tr>
							<th>
								<span class="custom-checkbox">
									<input type="checkbox" id="selectAll">
									<label for="selectAll"></label>
								</span>
							</th>
							<th>Product</th>
							<th>Category</th>
							<th>Size</th>
							<th>Type</th>
							<th>Price</th>
						</tr>
					</thead>
					<tbody> 
						
						<tr>
							<td>
								<span class="custom-checkbox">
									<input type="checkbox" id="checkbox1" name="options[]" value="{{ pr.id }}" onclick="myFunction()">
									<label for="checkbox1"></label>
								</span>
							</td>
							<td></td>
							<td></td>							
							<td></td>						
							<td></td>						
							<td></td>
							<td>
								 
								<span class="custom-checkbox">
									<input type="checkbox" id="{{ pr.id }}" name="options[]" value="" onclick="reply_click(this.id)">
									<label for="checkbox1"></label>
								</span>
							</td>
						</tr>
												
						
						
					</tbody>
				</table>
				<div class="clearfix">
					<div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
					<ul class="pagination">
						<li class="page-item disabled"><a href="#">Previous</a></li>
						<li class="page-item"><a href="#" class="page-link">1</a></li>
						<li class="page-item"><a href="#" class="page-link">2</a></li>
						<li class="page-item active"><a href="#" class="page-link">3</a></li>
						<li class="page-item"><a href="#" class="page-link">4</a></li>
						<li class="page-item"><a href="#" class="page-link">5</a></li>
						<li class="page-item"><a href="#" class="page-link">Next</a></li>
					</ul>
				</div>
			</div>
		</div>        
    </div>
	<!-- Edit Modal HTML -->
	<div id="addEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>
					<div class="modal-header">						
						<h4 class="modal-title">My Cart Items</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<div class="form-group">
							<label>Product</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Prize</label>
							<input type="email" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Address</label>
							<textarea class="form-control" required></textarea>
						</div>
						<div class="form-group">
							<label>Phone</label>
							<input type="text" class="form-control" required>
						</div>					
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-success" value="Add">
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- Edit Modal HTML -->
	<div id="editEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>
					<div class="modal-header">						
						<h4 class="modal-title">Edit Employee</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<div class="form-group">
							<label>Name</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Email</label>
							<input type="email" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Address</label>
							<textarea class="form-control" required></textarea>
						</div>
						<div class="form-group">
							<label>Phone</label>
							<input type="text" class="form-control" required>
						</div>					
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-info" value="Save">
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- Delete Modal HTML -->
	<div id="deleteEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>
					<div class="modal-header">						
						<h4 class="modal-title">Delete Employee</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<p>Are you sure you want to delete these Records?</p>
						<p class="text-warning"><small>This action cannot be undone.</small></p>
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-danger" value="Delete">
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

productapp/templates/productapp/product_index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title> {% block title %} Troo Product Home Page {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href=""><button type="button" class="btn btn-warning">Home</button></a></li>
			    <br>
          <br>          
          <li>You are logged in <br>User: <b>{{ user.get_username }}</b></li>
          <li><h3>GO for online shoping </h3></li>
          
          <li><a href="{% url 'productapp:prolist' %}"><button type="button" class="btn btn-secondary">Product List</button></a></li>                


       </ul>  
      {% endblock %}
      </div>

      <div class="col-sm-10 ">
      	<div align="right">
      	<a href=""><button type="button" class="btn btn-danger">Logout</button></a>	
		</div>
		{% block messages %}
		{% include 'messages.html'%}

		{% endblock %}
		<div class="container-fluid">
        {% block content %}
        <h1>Welcome to My home</h1>
        
        {% endblock %} 
        </div>    
      </div>
    </div>
  </div>
</body>
</html>